In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# graphic card name
torch.cuda.get_device_name(0)

'NVIDIA GeForce GTX 1650 Ti'

In [3]:
df = pd.read_csv('./Data/Iris.csv')

In [4]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df.shape

(150, 6)

In [6]:
df['Species'].unique()
#add a new column to the dataframe name 'target' and assign the value 0,1,2 based on the species
df['target'] = df['Species'].map({'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2})

### Label encoding

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
label_encoder = LabelEncoder()
df['Species'] = label_encoder.fit_transform(df['Species'])

In [9]:
df['Species'].unique()

array([0, 1, 2])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
features = df.drop("target", axis=1).values
label = df["target"].values

In [12]:
print(type(features))
print(type(label))
print(features.shape)
print(label.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(150, 6)
(150,)


In [13]:
X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=33)

In [14]:
X_train

array([[9.50e+01, 5.60e+00, 2.70e+00, 4.20e+00, 1.30e+00, 1.00e+00],
       [8.70e+01, 6.70e+00, 3.10e+00, 4.70e+00, 1.50e+00, 1.00e+00],
       [1.22e+02, 5.60e+00, 2.80e+00, 4.90e+00, 2.00e+00, 2.00e+00],
       [1.16e+02, 6.40e+00, 3.20e+00, 5.30e+00, 2.30e+00, 2.00e+00],
       [1.41e+02, 6.70e+00, 3.10e+00, 5.60e+00, 2.40e+00, 2.00e+00],
       [1.46e+02, 6.70e+00, 3.00e+00, 5.20e+00, 2.30e+00, 2.00e+00],
       [1.02e+02, 5.80e+00, 2.70e+00, 5.10e+00, 1.90e+00, 2.00e+00],
       [9.60e+01, 5.70e+00, 3.00e+00, 4.20e+00, 1.20e+00, 1.00e+00],
       [9.40e+01, 5.00e+00, 2.30e+00, 3.30e+00, 1.00e+00, 1.00e+00],
       [3.50e+01, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01, 0.00e+00],
       [8.80e+01, 6.30e+00, 2.30e+00, 4.40e+00, 1.30e+00, 1.00e+00],
       [9.30e+01, 5.80e+00, 2.60e+00, 4.00e+00, 1.20e+00, 1.00e+00],
       [9.80e+01, 6.20e+00, 2.90e+00, 4.30e+00, 1.30e+00, 1.00e+00],
       [3.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01, 0.00e+00],
       [7.00e+00, 4.60e+00, 3.40e+

In [15]:
# Convert the numpy array to tensor
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)

In [16]:
# y_train.shape
print('y_train',y_train[0:5])
print('y_test',y_test[0:5])

y_train tensor([[1],
        [1],
        [2],
        [2],
        [2]])
y_test tensor([[1],
        [1],
        [0],
        [1],
        [2]])


In [17]:
from torch.utils.data import DataLoader, TensorDataset

### Easy steps we can do this same by pytorch

In [18]:
df = pd.read_csv('./Data/Iris.csv')

In [19]:
df['target'] = df['Species'].map({'Iris-setosa':0, 'Iris-versicolor':1, 'Iris-virginica':2})
df['Species'] = label_encoder.fit_transform(df['Species'])

In [20]:
features = df.drop("target", axis=1).values
label = df["target"].values

In [21]:
iris = TensorDataset(torch.FloatTensor(features), torch.LongTensor(label))

In [22]:
type(iris)

torch.utils.data.dataset.TensorDataset

In [23]:
for i in iris[:5]:
    print(i)

tensor([[1.0000, 5.1000, 3.5000, 1.4000, 0.2000, 0.0000],
        [2.0000, 4.9000, 3.0000, 1.4000, 0.2000, 0.0000],
        [3.0000, 4.7000, 3.2000, 1.3000, 0.2000, 0.0000],
        [4.0000, 4.6000, 3.1000, 1.5000, 0.2000, 0.0000],
        [5.0000, 5.0000, 3.6000, 1.4000, 0.2000, 0.0000]])
tensor([0, 0, 0, 0, 0])


In [24]:
iris_loader = DataLoader(iris, 
                         batch_size=50,
                         shuffle=True)

In [25]:
len(iris_loader)
print(type(iris_loader))
# for batch in iris_loader:
#     print(batch)
# for i_batch, sample_batched in enumerate(iris_loader):
#     print(i_batch, sample_batched)

<class 'torch.utils.data.dataloader.DataLoader'>
