In [1]:
import torch

In the context of mathematics and machine learning, a derivative represents the rate at which a function is changing at any given point. It is a fundamental concept in calculus and is used extensively in optimization problems, including those in machine learning and deep learning.

### Key Points about Derivatives

1. **Definition**: The derivative of a function \( f(x) \) at a point \( x \) is defined as the limit of the average rate of change of the function over an interval as the interval approaches zero. Mathematically, it is expressed as:
   \[
   f'(x) = \lim_{\Delta x \to 0} \frac{f(x + \Delta x) - f(x)}{\Delta x}
   \]

2. **Notation**: The derivative of a function \( f \) with respect to \( x \) can be denoted in several ways:
   - \( f'(x) \)
   - \( \frac{df}{dx} \)
   - \( Df(x) \)

3. **Interpretation**: The derivative represents the slope of the tangent line to the function at a given point. It indicates how the function value changes as the input changes.

4. **Applications in Machine Learning**:
   - **Gradient Descent**: Derivatives are used to compute gradients, which are essential for optimization algorithms like gradient descent. Gradients indicate the direction and rate of fastest increase of a function.
   - **Backpropagation**: In neural networks, derivatives are used in the backpropagation algorithm to compute the gradients of the loss function with respect to the weights, allowing the network to learn by updating the weights.

### Example in PyTorch

In PyTorch, you can compute derivatives using automatic differentiation. Here's a simple example:





### Explanation of the Example

1. **Define a Tensor**: A tensor `x` is defined with `requires_grad=True`, which tells PyTorch to track all operations on this tensor.
2. **Define a Function**: A function \( y = x^2 \) is defined.
3. **Compute the Derivative**: The `backward()` method computes the derivative of `y` with respect to `x`.
4. **Print the Gradient**: The gradient (derivative) of `y` with respect to `x` is printed, which is \( 4 \) in this case because the derivative of \( x^2 \) is \( 2x \), and \( 2 \times 2 = 4 \).

This example demonstrates how to compute derivatives using PyTorch, which is a common task in training machine learning models.

In [5]:
import torch

# Define a tensor with requires_grad=True to track computations
x = torch.tensor(2.0, requires_grad=True)

# Define a function y = x^2
y = x ** 2
g = x ** 3
# Compute the derivative of y with respect to x
y.backward()

# Print the derivative (gradient) of y with respect to x
print(x.grad)  # Output: tensor(4.0)

tensor(4.)


In [18]:
import torch

In [19]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]], 
                 requires_grad=True, 
                 dtype=torch.float32)

In [20]:
y = x ** 2

In [21]:
print(y)

tensor([[ 1.,  4.,  9., 16.],
        [25., 36., 49., 64.]], grad_fn=<PowBackward0>)


In [22]:
out = y.mean()
print(out)

tensor(25.5000, grad_fn=<MeanBackward0>)


In [23]:
out.backward()

In [25]:
print(x)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], requires_grad=True)


In [26]:
print(x.grad)

tensor([[0.2500, 0.5000, 0.7500, 1.0000],
        [1.2500, 1.5000, 1.7500, 2.0000]])


In [32]:
import math

# Define the exponent
exponent = -0.5933

# Calculate e^(-0.3775)
result = math.exp(exponent)

# Print the result
print(f"The value of e^(-0.3775) is approximately: {result}")
# add + 1 and round to 4 decimal places
res = round(result + 1, 4)
print(res)

The value of e^(-0.3775) is approximately: 0.5525010196895426
1.5525


In [33]:
# Define the number
number = 1.6854

# Calculate the reciprocal
reciprocal = 1 / number

# Print the result
print(f"The reciprocal of {number} is approximately: {reciprocal}")

The reciprocal of 1.6854 is approximately: 0.5933309600094933
