In [1]:
import torch

In [2]:
import numpy as np

In [3]:
arry = np.arange(10)
print(arry)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
tens_array = torch.tensor(arry)

In [5]:
print(tens_array)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


In [9]:
# float tensor
f_tens = torch.Tensor(arry)

Tensor its a short for FloatTensor.

In [12]:
print(f_tens)
print(f_tens.dtype)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.float32


In [13]:
# torch.empty() creates a tensor with uninitialized

In [16]:
# torch.seros(4,3,dtype=torch.int64)
# torch.ones() creates a tensor with all ones
# torch.arage(0,18,2).reshape(3,3) creates a tensor with values from 0 to 18 with step 2 and reshapes it to 3x3
# torch.linspace(0,18,12).reshape(3,4) creates a tensor with 12 values from 0 to 18 and reshapes it to 3x4
# torch.rand(4,3) creates a tensor with random values between 0 and 1
# torch.randn(4,3) creates a tensor with random values from normal distribution
# torch.randperm(10) creates a tensor with random permutation of values from 0 to 9


In [26]:
torch.randperm(10)

tensor([5, 9, 8, 4, 2, 1, 3, 6, 0, 7])

In [34]:
n_s = torch.arange(10).reshape(5,-1)
print(n_s)
print(n_s.size())
print(n_s.dtype)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
torch.Size([5, 2])
torch.int64


In [25]:
my_tensor = torch.arange(10)
print(my_tensor)
print(my_tensor.dtype)
# change the dtype
my_tensor = my_tensor.type(torch.int32)
print(my_tensor.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.int64
torch.int32


In [35]:
new_dim=torch.randn_like(n_s,dtype=torch.float)
print(new_dim)

tensor([[-0.5224,  0.2880],
        [-0.9685, -2.0447],
        [ 1.3158, -0.9422],
        [ 2.0601,  0.3527],
        [-2.5403, -0.1651]])


In [38]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [6]:
# check card
print(torch.cuda.is_available())
# card name
print(torch.cuda.get_device_name())

True
NVIDIA GeForce GTX 1650 Ti


In [10]:
array_x = torch.tensor(np.arange(10))

In [13]:
array_x.device
# change to gpu
array_x = array_x.to('cuda')

In [14]:
array_x.device

device(type='cuda', index=0)

In [18]:
array_x = array_x.reshape(5,2)

In [34]:
array_x = torch.tensor(np.arange(10))

In [35]:
arr_view = array_x.reshape(2,5)

In [36]:
array_x = array_x ** 2

In [38]:
arr_view = array_x.reshape(2,5)

In [39]:
print(f"{array_x.shape} -> {arr_view.shape}")
print(f"{array_x.stride()} -> {arr_view.stride()}")
print(f"{array_x=}")
print(f"{arr_view=}")

torch.Size([10]) -> torch.Size([2, 5])
(1,) -> (5, 1)
array_x=tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=torch.int32)
arr_view=tensor([[ 0,  1,  4,  9, 16],
        [25, 36, 49, 64, 81]], dtype=torch.int32)


In [40]:
a = torch.tensor(np.arange(1,5))
b = torch.tensor(np.arange(5,9))
print(a)
print(b)

tensor([1, 2, 3, 4], dtype=torch.int32)
tensor([5, 6, 7, 8], dtype=torch.int32)


In [41]:
# dot product
dot_prod = torch.dot(a,b)
print(dot_prod)

tensor(70, dtype=torch.int32)


In [42]:
# matrix multiplication
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[2,0],[1,2]])
print(a)
print(b)

tensor([[1, 2],
        [3, 4]])
tensor([[2, 0],
        [1, 2]])


[1*2 + 2*1, 1*0 + 2*4],
[3*2 + 4*1, 3*0 +4*2]

[4, 4]
[10, 8]

In [43]:
torch.mm(a,b)

tensor([[ 4,  4],
        [10,  8]])

In [44]:
a @ b

tensor([[ 4,  4],
        [10,  8]])

In [45]:
# length of elements by numel,size,dim,length
a = torch.tensor(np.arange(1,10))
print(a)
print(a.numel())
print(a.size())
print(a.dim())
print(len(a))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)
9
torch.Size([9])
1
9


In [47]:
np_array = np.array([np.arange(1,5),
                    np.arange(5,9)])
print(f"{np_array=}")

np_array=array([[1, 2, 3, 4],
       [5, 6, 7, 8]])


In [49]:
# length of elements by numel,size,dim,length
print(len(np_array))
print(np_array.size)
print(np_array.ndim)

2
8
2
